
package org.arnotec.stub;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BankWS", targetNamespace = "http://ws.arnotec.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankWS {


    /**
     * 
     * @param code
     * @return
     *     returns org.arnotec.stub.Account
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccount", targetNamespace = "http://ws.arnotec.org/", className = "org.arnotec.stub.GetAccount")
    @ResponseWrapper(localName = "getAccountResponse", targetNamespace = "http://ws.arnotec.org/", className = "org.arnotec.stub.GetAccountResponse")
    @Action(input = "http://ws.arnotec.org/BankWS/getAccountRequest", output = "http://ws.arnotec.org/BankWS/getAccountResponse")
    public Account getAccount(
        @WebParam(name = "code", targetNamespace = "")
        Long code);

    /**
     * 
     * @return
     *     returns java.util.List<org.arnotec.stub.Account>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAccount", targetNamespace = "http://ws.arnotec.org/", className = "org.arnotec.stub.ListAccount")
    @ResponseWrapper(localName = "listAccountResponse", targetNamespace = "http://ws.arnotec.org/", className = "org.arnotec.stub.ListAccountResponse")
    @Action(input = "http://ws.arnotec.org/BankWS/listAccountRequest", output = "http://ws.arnotec.org/BankWS/listAccountResponse")
    public List<Account> listAccount();

    /**
     * 
     * @param amount
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "conversionEuroToFCFA", targetNamespace = "http://ws.arnotec.org/", className = "org.arnotec.stub.ConversionEuroToFCFA")
    @ResponseWrapper(localName = "conversionEuroToFCFAResponse", targetNamespace = "http://ws.arnotec.org/", className = "org.arnotec.stub.ConversionEuroToFCFAResponse")
    @Action(input = "http://ws.arnotec.org/BankWS/conversionEuroToFCFARequest", output = "http://ws.arnotec.org/BankWS/conversionEuroToFCFAResponse")
    public double conversionEuroToFCFA(
        @WebParam(name = "amount", targetNamespace = "")
        double amount);

}
